osx_image: xcode7.1
language: objective-c

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

script:
  - xctool -project LocativeBeacon.xcodeproj -scheme LocativeBeacon -destination name="iPhone 6s" -sdk iphonesimulator CODE_SIGN_ENTITLEMENTS="" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
